name: Hello World

# Trigger the workflow on push to main branch, pull requests, or via API
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger from GitHub UI
  workflow_dispatch:
  # Allow triggering via API calls
  repository_dispatch:
    types: [hello-world-trigger]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Say Hello World
      run: echo "Hello World"
